### ISSUE TITLE
Shortcut's don't working

### ISSUE THREAD

**Issue by jistake** [flathub/com.moonlight_stream.Moonlight#10]
Don't working shortcut's in flatpak app like Ctrl+Alt+Shift+S/Ctrl+Alt+Shift+Q and etc.
Fltatpak 1.12.7 version
Arch Linux 07.08.2022
Moonlight [v4.1.0]

**Comment by cgutman** [comment]
Hmm, I just gave it a try locally and they work properly for me on Fedora 36 with a QWERTY keyboard.

What keyboard layout are you using? Does the issue seem specific to the Flatpak version?

**Comment by jistake** [comment]
> Hmm, I just gave it a try locally and they work properly for me on Fedora 36 with a QWERTY keyboard.
> 
> What keyboard layout are you using? Is the issue specific to the Flatpak version?

I have just downloaded the Moonlight-Streaming app in the appimage version. And keyboard shortcuts work in both X11 and Wayland. This means that in this case the problem is specific to the flathub package in the Wayland environment.
I use locale for system Uk_ua.UTF-8 (Ukrainian), and use for language EN layout.

**Comment by cgutman** [comment]
Please try running Moonlight with this command `flatpak run --env=SDL_EVENT_LOGGING=1 com.moonlight_stream.Moonlight` then try to use the shortcuts while streaming and attach the log output here.

**Comment by jistake** [comment]
Hello. My output is here.
[moonlight-flatpak-log.txt](https://github.com/flathub/com.moonlight_stream.Moonlight/files/9309270/moonlight-flatpak-log.txt)


> Please try running Moonlight with this command `flatpak run --env=SDL_EVENT_LOGGING=1 com.moonlight_stream.Moonlight` then try to use the shortcuts while streaming and attach the log output here.

**Comment by cgutman** [comment]
OK, it looks like the `KMOD_LSHIFT` modifier is getting cleared when the Q key is pressed and that's why Moonlight doesn't recognize it.

```
00:00:12 - SDL Info (0): SDL EVENT: SDL_KEYDOWN (timestamp=12712 windowid=2 state=pressed repeat=false scancode=225 keycode=1073742049 mod=961)
00:00:12 - SDL Info (0): SDL EVENT: SDL_KEYMAPCHANGED
00:00:12 - SDL Info (0): SDL EVENT: SDL_KEYDOWN (timestamp=12937 windowid=2 state=pressed repeat=false scancode=20 keycode=1081 mod=960)
```

That last `SDL_KEYDOWN` should have `mod=961` (1 is the left shift modifier). I suspect it may be related to that unexpected `SDL_KEYMAPCHANGED` event that's received between the two key down events. I filed a bug on SDL to investigate the modifier flags https://github.com/libsdl-org/SDL/issues/6037 but I think I should be able to implement a workaround in Moonlight in the meantime.

**Comment by jistake** [comment]
> OK, it looks like the `KMOD_LSHIFT` modifier is getting cleared when the Q key is pressed and that's why Moonlight doesn't recognize it.
> 
> ```
> 00:00:12 - SDL Info (0): SDL EVENT: SDL_KEYDOWN (timestamp=12712 windowid=2 state=pressed repeat=false scancode=225 keycode=1073742049 mod=961)
> 00:00:12 - SDL Info (0): SDL EVENT: SDL_KEYMAPCHANGED
> 00:00:12 - SDL Info (0): SDL EVENT: SDL_KEYDOWN (timestamp=12937 windowid=2 state=pressed repeat=false scancode=20 keycode=1081 mod=960)
> ```
> 
> That last `SDL_KEYDOWN` should have `mod=961` (1 is the left shift modifier). I suspect it may be related to that unexpected `SDL_KEYMAPCHANGED` event that's received between the two key down events. I filed a bug on SDL to investigate the modifier flags [libsdl-org/SDL#6037](https://github.com/libsdl-org/SDL/issues/6037) but I think I should be able to implement a workaround in Moonlight in the meantime.

Well, at the moment for me the error is not critical. If more log files are needed for the fix, I will provide them.
