### ISSUE TITLE
flatpak runtime update results in no hardware decoders

### ISSUE THREAD

**Issue by DarkArc** [flathub/com.moonlight_stream.Moonlight#20]
mesa 22.2.4 has been shipped with a new `Mesa (Extra)` package containing the H264 and H265 decoder support.

```
$> flatpak list | grep -i .GL.default
...
Mesa	org.freedesktop.Platform.GL.default	22.2.4	22.08	system
Mesa (Extra)	org.freedesktop.Platform.GL.default	22.2.4	22.08-extra	system
```

This update breaks hardware acceleration within moonlight.

**Comment by cgutman** [comment]
Please try the test build from https://github.com/flathub/com.moonlight_stream.Moonlight/pull/21#issuecomment-1340492586

**Comment by DarkArc** [comment]
That does seem to fix it, thanks for the quick turn around!

**Comment by DarkArc** [comment]
I think this has been fixed by an upstream update to the KDE base.

**Comment by DarkArc** [comment]
Yes, I was surprised to see A) your quick response, and B) their quick turn around on a rebuild.

For your part, thank you very much!
